### ISSUE TITLE
ruh oh

### ISSUE THREAD

**Issue by Why2312** [MechSorcery/MechanicalSorcery#19]
# No health removed markers (created when damaging someone in e2e/e2eu), No quest line, no biomes o plenty, very ruh oh!!!!!!

**Comment by Apethesis** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh, wtf is health removed markers?

**Comment by Apethesis** [comment]
also no questline cause thats an asspain.

**Comment by 0mori1** [comment]
may i tweak the configuration of the spice of life carrot edition to be the same as e2eu

**Comment by 0mori1** [comment]
not much except making it one heart per 10 unique foods

**Comment by Apethesis** [comment]
yeah do that

**Comment by Apethesis** [comment]
everything but questline will be fixed, ty
