### ISSUE TITLE
illegal textures resulting in crash when breaking or punching a block belonging to SGCraft

### ISSUE THREAD

**Issue by GazaAudio** [MechSorcery/MechanicalSorcery#28]
stargate has missing textures when someone tries to break it, anyone near it or visually staring at it meets a white screen

**last 3 lines in the log when i punch a SGCraft block and meet the white screen:**
```
[22:40:07] [Client thread/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[22:40:07] [Client thread/ERROR] [net.minecraft.client.Minecraft]: @ LoliASM GUI Loop
[22:40:07] [Client thread/ERROR] [net.minecraft.client.Minecraft]: 1280: Invalid enum
```

tried to remove **Nothirium**, results in massive performance issue (0-1 frames per second)
tried to remove **Nothirium** and **censoredasm**, results in massive performance issue (0-1 frames per second)
tried to remove **SGCraft**, **Nothirium** and **censoredasm** and add **JSM**, results in massive loading time and frequent program not responding issues

final solution: give textures (the classic purple and black) to the **SGCraft** mod

**Comment by ADMIIM** [comment]
💀💀💀💀

**Comment by Apethesis** [comment]
and here you were telling me to install JSM

**Comment by Apethesis** [comment]
anyway i'll try figuring it out

**Comment by Apethesis** [comment]
okay so im looking at the source code and the textures
and i cannot figure it out
think we just have to live with crashing, atleast the modpack doesnt take years to start
